spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.126.130
    port: 5672
    username: admin
    password: admin

  zipkin:
    sender:
      type: rabbit
# 启动参数 --server.port 可以覆盖yml配置
server:
  port: 8001
  # 设置此处代表 启动时输入的参数 权重高于 git下的配置文件
  cloud:
    config:
      override-none: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka #,http://eureka3:2003/eureka
